
package frc.robot.constants;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj OutpostToMiddle = new ChoreoTraj(
	    "OutpostToMiddle",
	    OptionalInt.empty(),
	    2.21508,
	    new Pose2d(3.935, 0.43, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(7.979, 3.143, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj DepotToMiddle = new ChoreoTraj(
	    "DepotToMiddle",
	    OptionalInt.empty(),
	    2.19204,
	    new Pose2d(4.052, 7.659, Rotation2d.fromRadians(1.571)),
	    new Pose2d(7.81, 4.903, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj DepotBumpFromMiddle = new ChoreoTraj(
	    "DepotBumpFromMiddle",
	    OptionalInt.empty(),
	    1.31189,
	    new Pose2d(6.188, 5.57, Rotation2d.fromRadians(2.389)),
	    new Pose2d(2.427, 5.582, Rotation2d.fromRadians(2.389))
	);
	public static final ChoreoTraj OutpostBumpFromMiddle = new ChoreoTraj(
	    "OutpostBumpFromMiddle",
	    OptionalInt.empty(),
	    1.2306,
	    new Pose2d(6.098, 2.46, Rotation2d.fromRadians(2.465)),
	    new Pose2d(2.735, 2.483, Rotation2d.fromRadians(2.465))
	);
	public static final ChoreoTraj CollectDepot = new ChoreoTraj(
	    "CollectDepot",
	    OptionalInt.empty(),
	    1.46656,
	    new Pose2d(3.618, 4.042, Rotation2d.fromRadians(0)),
	    new Pose2d(0.66, 5.954, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj CollectOutpost = new ChoreoTraj(
	    "CollectOutpost",
	    OptionalInt.empty(),
	    2.92368,
	    new Pose2d(3.632, 4.046, Rotation2d.fromRadians(0)),
	    new Pose2d(0.641, 0.643, Rotation2d.fromRadians(0))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("OutpostToMiddle", OutpostToMiddle),
		Map.entry("DepotToMiddle", DepotToMiddle),
		Map.entry("DepotBumpFromMiddle", DepotBumpFromMiddle),
		Map.entry("OutpostBumpFromMiddle", OutpostBumpFromMiddle),
		Map.entry("CollectDepot", CollectDepot),
		Map.entry("CollectOutpost", CollectOutpost)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
